### ISSUE TITLE
Saving egg with temporary filename breaks metadata detection

### ISSUE THREAD

**Issue by kkremitzki** [enthought/okonomiyaki#326]
Example (with okonomiyaki 1.0.0):

```
$ hatcher eggs download enthought free win-x86 cp27 psutil 0.7.1-1
$ cp psutil-0.7.1-1.egg foo.egg
$ ipython
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

[nav] In [1]: from okonomiyaki.file_formats import EggMetadata

[ins] In [2]: md1 = EggMetadata.from_egg("psutil-0.7.1-1.egg")

[ins] In [3]: md2 = EggMetadata.from_egg("foo.egg")

[ins] In [4]: md1.platform_abi
Out[4]: PlatformABI(pep425_tag='msvc2008')

[ins] In [5]: md2.platform_abi is None
Out[5]: True

```

**Comment by kihneman** [comment]
This problem is occurring because okonomiyaki checks a blacklist to get additional info for really old eggs:
https://github.com/enthought/okonomiyaki/blob/master/okonomiyaki/file_formats/_blacklist/platform_tag.py

When the file name of the egg is changed, okonomiyaki can't find the egg name in the blacklist data. I talked to @kkremitzki and I think that he has another workaround for issues with these old Enthought eggs.

**Comment by kihneman** [comment]
@kkremitzki, I saved the PR to fix this which is referenced above. Are you sure that this does not need a fix? If so, I will close this issue as `wontfix`.

**Comment by itziakos** [comment]
Closing as wontfix
