### ISSUE TITLE
Drop `zipfile2` dependency on python 3

### ISSUE THREAD

**Issue by FFY00** [enthought/okonomiyaki#371]
`zipfile2` should not be needed on python 3, please drop the dependency in this version.

**Comment by itziakos** [comment]
Currently okonomiyaki mainly uses the context manager (which was added in stdlib on python 3.2) when the user provides a file path for the egg archive. So, while it is true that we could probably drop zipfile2 on python >= 3.2, I do not think that we should replace ZipFile2 with ZipFile for the following reasons:

- It would need to special case python < 3.2 and eventually use zipfile2. 
- zipfile does not claim have the same capabilities on symlinks as zipfile2 so dependent libraries might fail in unexpected ways due to these behavior differences.

Please note zipfile2 is a pure python thin layer on top of the stdlib zipfile. It adds a few capabilities and methods that have been quite useful and it is not specific to Python 2. For example offers read/write symlink support, a number of api extensions (see extractall) and new methods like (add_tree). These differences have been quite useful in the Enthought packaging ecosystem so we tend to use zipfile2 as a replacement for zipfile in all our code.

In anycase, is there something that causes problems with the use of zipfile2? Can you provide more info? It might be something that we can fix without removing/droping zipfile2.

**Comment by FFY00** [comment]
> zipfile2 contains an improved ZipFile class that may be used as a 100 % backward compatible replacement.

Well, if you are using the extra features provided by zipfile2 I think that makes sense, otherwise it could be dropped.

I am packaging okonomiyaki and adding an unneeded dependency is not desirable. Anyway, since you make use of the extra features, zipfile2 seems correct.

**Comment by itziakos** [comment]
> > zipfile2 contains an improved ZipFile class that may be used as a 100 % backward compatible replacement.
 
That is correct you can replace zipfile with zipfile2. But it is not always possible (or even desirable) to replace zipfile2 with zipfile because zipfile2 has more capabilities.

> I am packaging okonomiyaki and adding an unneeded dependency is not desirable. Anyway, since you make use of the extra features, zipfile2 seems correct.

Thanks, we will review the dependencies in our next release. I think that we can probably drop `six`.
